# Generated by Django 5.2.9 on 2026-01-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_contact_message_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_name', models.CharField(max_length=100, unique=True)),
                ('total_spots', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parking_lot',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('unknown', 'Unknown')], default='car', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('spot_number', models.CharField(max_length=10)),
                ('spot_type', models.CharField(choices=[('regular', 'Regular'), ('reserved', 'Reserved'), ('handicap', 'Handicap'), ('vip', 'VIP')], default='regular', max_length=50)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('spot_width', models.IntegerField(default=107)),
                ('spot_height', models.IntegerField(default=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parkingapp.parkinglot')),
            ],
            options={
                'db_table': 'parking_spot',
                'unique_together': {('parking_lot', 'spot_number')},
            },
        ),
        migrations.CreateModel(
            name='ParkedVehicle',
            fields=[
                ('parking_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('entry_image_path', models.FileField(blank=True, null=True, upload_to='parking_images/entry/')),
                ('exit_image_path', models.FileField(blank=True, null=True, upload_to='parking_images/exit/')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.parkingspot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_history', to='parkingapp.vehicle')),
            ],
            options={
                'db_table': 'parked_vehicle',
                'ordering': ['-checkin_time'],
                'indexes': [models.Index(fields=['vehicle', 'checkout_time'], name='parked_vehi_vehicle_52e261_idx'), models.Index(fields=['parking_spot', 'checkout_time'], name='parked_vehi_parking_dd55d3_idx'), models.Index(fields=['checkin_time'], name='parked_vehi_checkin_036366_idx')],
            },
        ),
    ]
