# Generated by Django 6.0.1 on 2026-01-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_parkinglot_vehicle_parkingspot_parkedvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSyncQueue',
            fields=[
                ('sync_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50)),
                ('vehicle_id', models.IntegerField(null=True)),
                ('parking_spot_id', models.IntegerField(null=True)),
                ('data', models.JSONField()),
                ('synced', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_sync_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('force_release', 'Force Release Spot'), ('manual_entry', 'Manual Vehicle Entry'), ('manual_exit', 'Manual Vehicle Exit'), ('override_detection', 'Override Detection'), ('mark_double_parked', 'Mark as Double Parked'), ('resolve_dispute', 'Resolve Dispute'), ('camera_maintenance', 'Camera Maintenance')], max_length=50)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.parkingspot')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.vehicle')),
            ],
            options={
                'db_table': 'admin_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], db_index=True, default='online', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
                ('spot_coverage', models.ManyToManyField(related_name='cameras', to='parkingapp.parkingspot')),
            ],
            options={
                'db_table': 'camera_status',
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('frame_image', models.ImageField(upload_to='detection_frames/')),
                ('vehicles_detected', models.IntegerField()),
                ('confidence_scores', models.JSONField()),
                ('license_plates', models.JSONField()),
                ('plate_confidence', models.JSONField()),
                ('manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.camerastatus')),
            ],
            options={
                'db_table': 'detection_log',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeLog',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('dispute_type', models.CharField(choices=[('car_not_found', 'Car Not Found at Spot'), ('wrong_spot', 'Wrong Spot Assigned'), ('damage', 'Vehicle Damaged'), ('double_charge', 'Double Charged'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('entry_image', models.FileField(blank=True, null=True, upload_to='dispute_images/entry/')),
                ('entry_video', models.FileField(blank=True, null=True, upload_to='dispute_videos/entry/')),
                ('detection_confidence', models.FloatField(default=0.95)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved_refund', 'Resolved - Refund Issued'), ('resolved_valid', 'Resolved - Record Valid'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Management')], default='pending', max_length=50)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('parked_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkedvehicle')),
            ],
            options={
                'db_table': 'dispute_log',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('ticket_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ticket_qr', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('parked_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkedvehicle')),
            ],
            options={
                'db_table': 'parking_history',
                'ordering': ['-parked_vehicle__checkin_time'],
            },
        ),
    ]
