# Generated by Django 5.2.9 on 2026-01-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0005_pendingsyncqueue_adminaction_camerastatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ParkingLotSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('enable_reservations', models.BooleanField(default=True)),
                ('enable_dynamic_pricing', models.BooleanField(default=False)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='parkingapp.parkinglot')),
            ],
            options={
                'db_table': 'parking_lot_settings',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('van', 'Van')], default='car', max_length=20)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parkingapp.parkinglot')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='parkingapp.user_details')),
            ],
            options={
                'db_table': 'parking_sessions',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('digital_wallet', 'Digital Wallet'), ('cash', 'Cash'), ('monthly_pass', 'Monthly Pass')], default='credit_card', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parkingapp.parkingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parkingapp.user_details')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_hour_free', models.BooleanField(default=False)),
                ('max_daily_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='parkingapp.parkinglot')),
            ],
            options={
                'db_table': 'pricing_rules',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('spot_available', 'Spot Available'), ('parking_expiring', 'Parking Expiring Soon'), ('payment_due', 'Payment Due'), ('reservation_reminder', 'Reservation Reminder'), ('parking_complete', 'Parking Complete'), ('promotion', 'Promotion'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('in_app', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parkingapp.user_details')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('peak_occupancy_percent', models.IntegerField(default=0)),
                ('average_duration_minutes', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='parkingapp.parkinglot')),
            ],
            options={
                'db_table': 'parking_analytics',
                'ordering': ['-date'],
                'unique_together': {('parking_lot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('vehicle_type', models.CharField(default='car', max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkingapp.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parkingapp.user_details')),
            ],
            options={
                'db_table': 'parking_reservations',
                'ordering': ['-created_at'],
                'unique_together': {('parking_spot', 'reserved_from', 'reserved_until')},
            },
        ),
    ]
